export const UserData = [
    {
        id: 1,
        month: 'Jan',
        hadir: 11,
        terlambat: 1,
        tidakhadir: 7,
        izin: 0,
        performance: 76,
        result: 'Cukup Bagus',
    },
    {
        id: 2,
        month: 'Feb',
        hadir: 12,
        terlambat: 0,
        tidakhadir: 9,
        izin: 0,
        performance: 66,
        result: 'Kurang Bagus',
    },
    {
        id: 3,
        month: 'Mar',
        hadir: 0,
        terlambat: 0,
        tidakhadir: 0,
        izin: 0,
        performance: 0,
        result: 'Sangat Tidak Bagus',
    },
    {
        id: 4,
        month: 'Apr',
        hadir: 0,
        terlambat: 0,
        tidakhadir: 0,
        izin: 0,
        performance: 0,
        result: 'Sangat Tidak Bagus',
    },
    {
        id: 5,
        month: 'Mei',
        hadir: 0,
        terlambat: 0,
        tidakhadir: 0,
        izin: 0,
        performance: 0,
        result: 'Sangat Tidak Bagus',
    },
    {
        id: 6,
        month: 'Jun',
        hadir: 0,
        terlambat: 0,
        tidakhadir: 0,
        izin: 0,
        performance: 0,
        result: 'Sangat Tidak Bagus',
    },
];
